<!-- popup-working.phtml -->
<div id="popup-working" class="working-popup" style="display:none;">
    <div class="working-container">

        <div class="working-content">
            <span class="loading"></span>
            <p>Trabalhando nisso...</p>
        </div>

        <div class="preview-square">
            <button type="button" class="delete-draw"></button>
            <img id="uploaded-preview" src="" alt="Preview da imagem"/>
            <button type="button" class="refresh-draw"></button>
            <button type="button" class="add-cart"></button>
        </div>
    </div>
</div>

<script>
    window.BASE_URL = '<?= $block->getBaseUrl() ?>';
</script>